export const moviesData = [
  {
    id: 27,
    title: "The Million-dollar Pentagram",
    year: 2024,
    rating: 4.9,
    bg: "https://i.pinimg.com/1200x/8c/f5/05/8cf5053b0aa7e6f6d696a58688c3bd76.jpg",
    desc: "Di Hakodate, Kaito Kid mengincar sepasang pedang Jepang bersejarah milik keluarga Onoe. Namun, pedang tersebut ternyata menyimpan rahasia besar tentang harta karun tersembunyi yang dicari oleh pedagang senjata internasional. Conan dan Heiji Hattori harus bekerja sama untuk memecahkan teka-teki rumit ini sambil menghadapi persaingan deduksi yang sengit di bawah langit Hokkaido.",
  },
  {
    id: 26,
    title: "Black Iron Submarine",
    year: 2023,
    rating: 4.8,
    bg: "https://i.pinimg.com/1200x/0c/47/3c/0c473c1d1314f33bcd2c6cf7a21184e9.jpg",
    desc: "Fasilitas Interpol bawah laut bernama Pacific Buoy yang memiliki sistem pengenalan wajah global menjadi target utama Organisasi Hitam. Gin dan kawan-kawan berusaha menculik staf ahli dan mengincar Ai Haibara setelah identitas aslinya terancam terbongkar. Conan harus melakukan aksi penyelamatan berbahaya di kedalaman laut demi melindungi teman-temannya dari ancaman organisasi yang paling ia takuti.",
  },
  {
    id: 25,
    title: "The Bride of Halloween",
    year: 2022,
    rating: 4.7,
    bg: "https://i.pinimg.com/1200x/26/62/b6/2662b682b62cd79676cb8ba41aa04ec3.jpg",
    desc: "Di tengah perayaan Halloween yang meriah di Shibuya, sebuah konspirasi bom yang melibatkan penjahat legendaris dari masa lalu kembali muncul. Kejadian ini membawa kembali kenangan pahit tentang akademi kepolisian dan rekan-rekan Rei Furuya yang telah gugur. Conan harus membantu Amuro mengungkap identitas pembom misterius 'Plamya' sebelum seluruh distrik Shibuya hancur dalam ledakan dahsyat.",
  },
  {
    id: 24,
    title: "The Scarlet Bullet",
    year: 2021,
    rating: 4.5,
    bg: "https://i.pinimg.com/1200x/20/c6/11/20c6117cbd73b736baa80c51217c7bea.jpg",
    desc: "Dunia sedang menantikan World Sports Games di Tokyo, bersamaan dengan peluncuran kereta peluru Hyper Linear yang mampu melaju dengan kecepatan luar biasa. Namun, serangkaian penculikan eksekutif sponsor mulai terjadi, sangat mirip dengan insiden di Amerika 15 tahun lalu. Conan bekerja sama dengan keluarga Akai yang misterius untuk menghentikan sabotase yang mengancam nyawa ribuan penumpang kereta tersebut.",
  },
  {
    id: 23,
    title: "The Fist of Blue Sapphire",
    year: 2019,
    rating: 4.4,
    bg: "https://i.pinimg.com/1200x/ed/49/86/ed4986a0b60ce8139b78427310153b2a.jpg",
    desc: "Kasus pembunuhan di Marina Bay Sands membawa Conan ke Singapura di bawah identitas baru sebagai Arthur Hirai. Permata legendaris 'Blue Sapphire' yang tenggelam di dasar laut menjadi pusat konflik antara Kaito Kid, pakar karate Makoto Kyogoku, dan musuh tersembunyi yang ingin menghancurkan Singapura. Pertarungan seni bela diri dan tipu muslihat Kid menciptakan kekacauan di kota singa tersebut.",
  },
  {
    id: 22,
    title: "Zero the Enforcer",
    year: 2018,
    rating: 4.6,
    bg: "https://i.pinimg.com/736x/52/17/a4/5217a478cd45f2e7ab0dab2d50a8d377.jpg",
    desc: "Ledakan mendadak di fasilitas Edge of Ocean saat pertemuan puncak internasional menyebabkan Kogoro Mouri ditangkap sebagai tersangka utama. Conan harus berhadapan dengan Tooru Amuro, yang tampaknya bekerja di balik layar demi kepentingan nasional. Di tengah serangan siber global dan ancaman satelit yang akan jatuh ke bumi, Conan harus mengungkap kebenaran di balik keadilan absolut milik Zero.",
  },
  {
    id: 21,
    title: "The Crimson Love Letter",
    year: 2017,
    rating: 4.5,
    bg: "https://i.pinimg.com/736x/d8/9b/8f/d89b8f7412f80550d1c19127d8c62940.jpg",
    desc: "Kasus pengeboman di stasiun TV Nichiuri bertepatan dengan turnamen kartu Karuta. Seorang gadis bernama Momiji Ooka muncul dan mengaku sebagai tunangan Heiji Hattori, memicu persaingan sengit dengan Kazuha Toyama. Conan dan Heiji harus memecahkan misteri pembunuhan juara Karuta sambil melindungi orang-orang yang mereka cintai di tengah tradisi kartu puisi yang berdarah di Kyoto dan Osaka.",
  },
  {
    id: 20,
    title: "The Darkest Nightmare",
    year: 2016,
    rating: 4.8,
    bg: "https://i.pinimg.com/736x/95/8b/5b/958b5b8945a24a0b3fb4eaec23c7e3ab.jpg",
    desc: "Seorang agen wanita dari Organisasi Hitam mengalami amnesia setelah aksi kejar-kejaran mobil yang hebat. Saat Conan dan Grup Detektif Cilik mencoba membantunya di taman bermain, para anggota elit organisasi seperti Gin dan Vermouth mulai bergerak untuk menjemputnya. Pertarungan besar antara CIA, FBI, PSB, dan Organisasi Hitam pecah di atas kincir ria raksasa, mengancam keselamatan semua orang.",
  },
  {
    id: 19,
    title: "Sunflowers of Inferno",
    year: 2015,
    rating: 4.1,
    bg: "https://i.pinimg.com/1200x/a7/fd/4d/a7fd4d0010a152cdcb97cd22beb08e22.jpg",
    desc: "Jirokichi Suzuki berhasil memenangkan lelang lukisan 'Sunflowers' karya Van Gogh yang dianggap telah hancur saat Perang Dunia II. Kaito Kid tiba-tiba muncul dan menyatakan akan mencuri lukisan tersebut dengan cara yang jauh lebih agresif dari biasanya. Conan merasa ada yang aneh dengan perilaku Kid, sementara kebakaran besar mengancam museum seni modern yang dirancang khusus untuk melindungi lukisan legendaris tersebut.",
  },
  {
    id: 18,
    title: "Dimensional Sniper",
    year: 2014,
    rating: 4.5,
    bg: "https://i.pinimg.com/1200x/a3/e8/dd/a3e8dd3bb307bb093ae0cc57b49b6288.jpg",
    desc: "Seorang penembak jitu misterius mulai menargetkan mantan anggota pasukan khusus Amerika di Tokyo. Jarak tembak yang luar biasa jauh membuat polisi kewalahan, dan FBI ikut turun tangan dalam penyelidikan ini. Conan harus bekerja sama dengan Subaru Okiya untuk menghentikan sang sniper, sementara rahasia besar mengenai identitas seseorang yang seharusnya sudah 'mati' mulai terkuak di Bell Tree Tower.",
  },
  {
    id: 17,
    title: "Private Eye in the Distant Sea",
    year: 2013,
    rating: 4.0,
    bg: "https://i.pinimg.com/1200x/5d/8c/83/5d8c83d811df36d6e7e97f60b016ac7e.jpg",
    desc: "Saat mengikuti tur kapal perusak Aegis milik Angkatan Laut Jepang, Conan menemukan potongan lengan manusia yang tertinggal di dalam filter air kapal. Ternyata, seorang mata-mata bernama 'X' telah menyusup ke dalam kapal untuk mencuri data rahasia pertahanan negara. Di tengah ketegangan militer di laut lepas, Conan harus menemukan mata-mata tersebut sebelum Ran jatuh ke dalam bahaya yang mengancam nyawanya di lautan.",
  },
  {
    id: 16,
    title: "The Eleventh Striker",
    year: 2012,
    rating: 4.2,
    bg: "https://i.pinimg.com/736x/35/60/e8/3560e8944a56c405947678ef5d289c51.jpg",
    desc: "Kogoro Mouri menerima ancaman bom misterius yang melibatkan stadion sepak bola J-League. Sang pelaku memberikan kode rumit yang harus dipecahkan untuk menghentikan ledakan saat pertandingan sedang berlangsung. Conan harus memanfaatkan kemampuan analisisnya dan kemahiran bermain bola untuk menemukan lokasi bom terakhir yang disembunyikan di tengah kerumunan ribuan penonton stadion.",
  },
  {
    id: 15,
    title: "Quarter of Silence",
    year: 2011,
    rating: 4.4,
    bg: "https://i.pinimg.com/736x/f5/ba/c2/f5bac2b2e2fb4e023659a12a7340ea7d.jpg",
    desc: "Setelah ancaman bom di jalur kereta bawah tanah Tokyo, Conan mencurigai adanya hubungan dengan sebuah desa di pegunungan salju yang baru saja memindahkan bendungan. Di sana, mereka bertemu dengan sekelompok teman lama yang menyimpan rahasia tentang kecelakaan tragis delapan tahun lalu. Conan harus berpacu dengan waktu untuk mencegah bencana banjir besar akibat ledakan bendungan yang dapat menyapu seluruh desa.",
  },
  {
    id: 14,
    title: "The Lost Ship in the Sky",
    year: 2010,
    rating: 4.6,
    bg: "https://i.pinimg.com/1200x/4b/12/7c/4b127c492c447669a46073cfe273115b.jpg",
    desc: "Kaito Kid kembali menantang Jirokichi Suzuki untuk mencuri permata di atas kapal balon udara raksasa, 'Bell Tree First'. Namun, sekelompok teroris 'Red Siamese Cat' membajak kapal tersebut dan mengklaim telah melepaskan virus mematikan. Conan yang terlempar keluar dari kapal harus menemukan cara untuk kembali ke atas, mengalahkan para teroris, dan bekerja sama secara tak terduga dengan Kaito Kid.",
  },
  {
    id: 13,
    title: "The Raven Chaser",
    year: 2009,
    rating: 4.7,
    bg: "https://i.pinimg.com/736x/00/1d/fb/001dfbefb3b6afbbab51320420517ff8.jpg",
    desc: "Serangkaian pembunuhan berantai terjadi di berbagai prefektur Jepang. Conan menyadari bahwa Organisasi Hitam terlibat ketika ia menemukan anggota baru bernama Irish telah menyusup ke dalam kepolisian dan mengetahui identitas aslinya. Dalam pertarungan hidup dan mati di Menara Tokyo, Conan harus menghadapi helikopter tempur Organisasi Hitam sambil berusaha melindungi rahasia identitasnya agar tidak membahayakan orang-orang di sekitarnya.",
  },
  {
    id: 12,
    title: "Full Score of Fear",
    year: 2008,
    rating: 4.2,
    bg: "https://i.pinimg.com/1200x/91/a2/ef/91a2efcc32e295ae1230d53299bf441c.jpg",
    desc: "Seorang penyanyi sopran terkenal menjadi target pembunuhan berantai yang mengincar para musisi akademi musik ternama. Saat peresmian gedung konser baru, Conan dan sang penyanyi diculik dan ditinggalkan di tengah waduk. Conan harus menggunakan pengetahuan musiknya yang terbatas serta frekuensi suara untuk memberikan sinyal darurat, sekaligus menghentikan ledakan besar yang dipicu oleh nada organ pipa di dalam gedung konser.",
  },
  {
    id: 11,
    title: "Jolly Roger in the Deep Azure",
    year: 2007,
    rating: 4.0,
    bg: "https://i.pinimg.com/736x/ac/3e/a9/ac3ea929f27affaeb9597b1f4cb32379.jpg",
    desc: "Di Pulau Koumi, sebuah legenda tentang harta karun yang ditinggalkan oleh dua bajak laut wanita, Anne Bonny dan Mary Read, menarik perhatian para pemburu harta. Conan dan teman-temannya harus berhadapan dengan pemburu harta yang kejam di sebuah reruntuhan bawah laut. Ran dan Sonoko harus menunjukkan keberanian luar biasa seperti para bajak laut legenda saat mereka terjebak dalam gua yang mulai kehilangan oksigen.",
  },
  {
    id: 10,
    title: "The Private Eyes' Requiem",
    year: 2006,
    rating: 4.3,
    bg: "https://i.pinimg.com/736x/6a/2d/89/6a2d89e6e1411380c930c1d0dcc0bb6c.jpg",
    desc: "Kogoro Mouri dan Conan diundang oleh klien misterius ke taman bermain Miracle Land di Yokohama. Tanpa disadari, Ran dan Grup Detektif Cilik diberikan gelang berisi bom yang akan meledak jika mereka keluar dari taman tersebut atau jika kasus tidak terpecahkan dalam 12 jam. Conan harus berpacu dengan waktu bersama Heiji dan Hakuba Saguru untuk memecahkan misteri terakhir yang sangat berbahaya.",
  },
  {
    id: 9,
    title: "Strategy Above the Depths",
    year: 2005,
    rating: 4.2,
    bg: "https://i.pinimg.com/736x/f6/50/a5/f650a58d55ed6053f593d42b83b1f606.jpg",
    desc: "Di atas kapal pesiar mewah Aphrodite, sebuah rencana pembunuhan berantai yang rapi dijalankan sebagai bentuk balas dendam atas tragedi kapal karam 15 tahun silam. Conan berusaha menghentikan pelaku yang sangat cerdik, sementara Kogoro Mouri secara mengejutkan menunjukkan kemampuannya yang luar biasa karena tersangka memiliki kemiripan dengan istrinya. Situasi menjadi kritis saat kapal mulai tenggelam dan Ran terjebak di dalamnya.",
  },
  {
    id: 8,
    title: "Magician of the Silver Sky",
    year: 2004,
    rating: 4.4,
    bg: "https://i.pinimg.com/736x/4b/4e/6e/4b4e6ec2586100273054c1bbc7ba20f3.jpg",
    desc: "Seorang aktris teater meminta bantuan Kogoro untuk melindungi cincin safir 'Destiny Jewel' dari incaran Kaito Kid. Selama penerbangan menuju Hakodate, sang aktris tewas karena racun, dan pilot pesawat pun ikut tidak sadarkan diri. Dalam situasi darurat di udara, Conan harus bekerja sama dengan musuh bebuyutannya, Kaito Kid, untuk mendaratkan pesawat di tengah badai sebelum bahan bakar habis.",
  },
  {
    id: 7,
    title: "Crossroad in the Ancient Capital",
    year: 2003,
    rating: 4.6,
    bg: "https://i.pinimg.com/736x/18/28/39/182839569514bf1c583c7eb5d6dc53d9.jpg",
    desc: "Pembunuhan berantai anggota kelompok pencuri seni 'Genjibotaru' terjadi di beberapa kota besar. Conan yang sedang berada di Kyoto bertemu dengan Heiji Hattori yang juga sedang mencari cinta pertamanya di kota yang sama. Mereka berdua harus memecahkan kode rahasia dari gambar kuno untuk menemukan patung Buddha yang hilang dan mengungkap identitas pembunuh bertopeng yang sangat mahir menggunakan pedang.",
  },
  {
    id: 6,
    title: "The Phantom of Baker Street",
    year: 2002,
    rating: 4.9,
    bg: "https://i.pinimg.com/736x/16/3b/68/163b6852dfd013e03d1250378e79b536.jpg",
    desc: "Conan dan teman-temannya menguji coba sistem virtual reality 'Cocoon', namun sistem tersebut dibajak oleh kecerdasan buatan 'Noah's Ark'. Jika tidak ada satupun pemain yang menang, semua anak akan mati di dunia nyata. Conan memilih skenario London tahun 1888 untuk memburu Jack the Ripper dengan bantuan tokoh fiksi Sherlock Holmes demi menyelamatkan nyawa teman-temannya dari ancaman maut di dunia digital.",
  },
  {
    id: 5,
    title: "Countdown to Heaven",
    year: 2001,
    rating: 4.7,
    bg: "https://i.pinimg.com/736x/ef/10/c5/ef10c5e08f3e48745e3fe61ece9631ed.jpg",
    desc: "Gedung pencakar langit kembar tertinggi di Nishitama menjadi lokasi pembunuhan berantai yang melibatkan dewan kota. Di saat yang sama, Organisasi Hitam mencurigai keberadaan Ai Haibara di gedung tersebut dan memasang bom di setiap sudut. Conan harus melakukan aksi nekat melompati gedung dengan mobil untuk menyelamatkan Grup Detektif Cilik dari kobaran api dan ledakan besar yang telah direncanakan Gin.",
  },
  {
    id: 4,
    title: "Captured in Her Eyes",
    year: 2000,
    rating: 4.6,
    bg: "https://i.pinimg.com/736x/73/23/fd/7323fd35e95ac30116b447c9ade5a41d.jpg",
    desc: "Seorang pembunuh berantai menargetkan perwira kepolisian, dan Ran secara tragis menyaksikan penembakan detektif Sato. Akibat syok berat, Ran mengalami amnesia total dan kehilangan ingatannya tentang semua orang, termasuk Conan. Karena Ran adalah saksi kunci yang bisa mengenali wajah pelaku, nyawanya kini dalam bahaya besar. Conan harus melindungi Ran di taman bermain Tropical Land sambil mencoba mengembalikan ingatannya.",
  },
  {
    id: 3,
    title: "The Last Wizard of the Century",
    year: 1999,
    rating: 4.5,
    bg: "https://i.pinimg.com/736x/f2/ec/85/f2ec85b3ebdb4c3f5d5e408ee323966c.jpg",
    desc: "Kaito Kid mencuri 'Imperial Easter Egg' milik dinasti Romanov Rusia, namun ia ditembak oleh pembunuh misterius yang dikenal sebagai 'Scorpion'. Conan segera melakukan penyelidikan di sebuah kastil tua yang menyimpan rahasia tentang pembuat telur tersebut. Di sini, sejarah masa lalu dan identitas asli Shinichi Kudo terancam terbongkar di hadapan Kaito Kid dan musuh yang mengincar harta warisan Tsar tersebut.",
  },
  {
    id: 2,
    title: "The Fourteenth Target",
    year: 1998,
    rating: 4.3,
    bg: "https://i.pinimg.com/736x/8f/a3/a3/8fa3a3bf3981a92151303485bfe07269.jpg",
    desc: "Orang-orang yang memiliki hubungan dekat dengan Kogoro Mouri diserang satu per satu. Conan menyadari bahwa para korban dipilih berdasarkan nama yang mengandung angka dari kartu remi, mulai dari raja (13) hingga as (1). Kasus ini membuka luka lama tentang alasan Kogoro keluar dari kepolisian setelah insiden penembakan sandera yang melibatkan istrinya, Eri Kisaki, bertahun-tahun yang lalu.",
  },
  {
    id: 1,
    title: "The Time-Bombed Skyscraper",
    year: 1997,
    rating: 4.5,
    bg: "https://i.pinimg.com/1200x/51/f3/9b/51f39bc52e04b4ccbf1dc9a8799e7a92.jpg",
    desc: "Seorang arsitek terkenal yang terobsesi dengan simetri menantang Shinichi Kudo melalui teror bom di berbagai lokasi di Tokyo. Puncaknya, sebuah gedung bioskop tempat Ran sedang menunggu kencan dengan Shinichi dipasangi bom besar. Conan harus memandu Ran melalui telepon untuk menjinakkan kabel bom terakhir dalam situasi yang sangat menegangkan, di mana pilihan antara kabel merah dan biru menentukan nasib mereka.",
  },
];

export const getMovieById = (id) =>
  moviesData.find((m) => m.id === parseInt(id));
